name: 'NUnit HTML Report'
description: 'Generates an HTML report from NUnit XML test results'
inputs:
  inputXmlPath:
    description: 'XML input file path'
    required: true
  outputHtmlPath:
    description: 'HTML output file path'
    default: ''
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Replace with the desired Python version

    - run: python -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: cmd

    - run: python ${{ github.action_path }}/main.py ${{ inputs.inputXmlPath }} ${{ inputs.outputHtmlPath }}
      shell: cmd

branding:
  icon: 'file'
  color: 'green'
